//
//  OKRulesView
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.


#import <UIKit/UIKit.h>

/// 最小刻度值
UIKIT_EXTERN const CGFloat OKMinScale;
/// 最大刻度值
UIKIT_EXTERN const CGFloat OKMaxScale;
/// 每个刻度值
UIKIT_EXTERN const CGFloat OKAvgScale;
/// 刻度之间的间距
UIKIT_EXTERN const CGFloat OKScalePadding;
/// 间隔刻度显示
UIKIT_EXTERN const CGFloat OKShowValueScale;

/// 游标颜色
#define OKPointColor [UIColor redColor]
/// 刻度线颜色
#define OKLineColor [UIColor blackColor]

@interface OKRulesScrollView : UIScrollView

@end
